version: '3.8'
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    user: '1000'
    ports:
      - '3001:3000'
    volumes:
      - './data/grafana:/var/lib/grafana'

  database:
    build:
        context: ./postgres
        dockerfile: Dockerfile
    image: 'database'
    container_name: 'database'
    restart: unless-stopped
    user: '1000'
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
       - ./data/postgres:/var/lib/postgresql/data

  script:
    build:
        context: ./script
        dockerfile: Dockerfile
    image: 'script'
    container_name: 'script'
    restart: unless-stopped
    environment:
      PGCONTAINER: database